employee/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "employee"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('updatestatus/<int:id>',views.updatestatus,name = "updatestatus"),
    path('updatedue/<int:id>',views.updatedue,name = "updatedue"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('p_manager/',include("p_manager.urls",namespace = 'p_manager')),
    path('project/',include("project.urls",namespace = 'project')),
    path('employee/',include("employee.urls",namespace = 'employee')),
    path('user/',include("user.urls",namespace = 'user')),
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "project"

urlpatterns = [
    #path('projectdetail/<int:id>',views.projectdetail,name = "projectdetail"),
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('projects/',views.projectsPage,name="projects"),
    path('detail/<int:id>',views.projectDetail,name="projectDetail"),
    path('comment/<int:id>',views.addComment,name = "comment")
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('logout/',views.logoutUser,name = "logoutUser"),
    path('login/',views.loginUser,name = "loginUser"),
    
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Derin Team</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'project:projects' %}">Projeler</a>
        </li>


      </ul>
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logoutUser' %}">Çıkış Yap</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'project:dashboard' %}">Kontrol Paneli</a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:loginUser' %}">Giriş Yap</a>
        </li>

        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Üye Ol
          </a>
          <ul class="dropdown-menu"  style="right: 0; left: auto;" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'p_manager:register'  %}"> Üye Ol(Yönetici)</a></li>
            <li><a class="dropdown-item" href="{% url 'employee:register'  %}"> Üye Ol(Çalışan)</a></li>

          </ul>
        </li>
        
      </ul>


      {% endif %}
    </div>
  </div>
</nav>