employee/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "employee"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('updatestatus/<int:id>',views.updatestatus,name = "updatestatus"),
    path('updatedue/<int:id>',views.updatedue,name = "updatedue"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('p_manager/',include("p_manager.urls",namespace = 'p_manager')),
    path('project/',include("project.urls",namespace = 'project')),
    path('employee/',include("employee.urls",namespace = 'employee')),
    path('user/',include("user.urls",namespace = 'user')),
]

p_manager/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "p_manager"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('addprojects/',views.addprojects,name = "addprojects"),
    path('updateprojects/<int:id>',views.updateprojects,name = "updateprojects"),
    path('deleteprojects/<int:id>',views.deleteprojects,name = "deleteprojects"),
    path('addtask/',views.addtask,name = "addtask"),
    path('updateTask/<int:id>',views.updateTask,name="updateTask"),
    path('deleteTask/<int:id>',views.deleteTask,name="deleteTask")
]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "project"

urlpatterns = [
    #path('projectdetail/<int:id>',views.projectdetail,name = "projectdetail"),
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('projects/',views.projectsPage,name="projects"),
    path('detail/<int:id>',views.projectDetail,name="projectDetail"),
    path('comment/<int:id>',views.addComment,name = "comment")
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('logout/',views.logoutUser,name = "logoutUser"),
    path('login/',views.loginUser,name = "loginUser"),
    
]

project/models.py
from django.db import models
from p_manager.models import ProjectManager
from employee.models import Employee
from p_manager.models import Company
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
status = (
    ('1', 'Durdu'),
    ('2', 'Çalışıyor'),
    ('3', 'Bitti'),
)

due = (
    ('1', 'Zamanı Yaklaşıyor'),
    ('2', 'Zamanı Aştı'),
    ('3', 'Bitti'),
)


class Projects(models.Model):

    projectManager = models.ForeignKey(
        ProjectManager, on_delete=models.CASCADE, verbose_name="Projenin Yöneticisi")
    projectName = models.CharField(max_length=100, verbose_name="Proje İsmi")
    employees = models.ManyToManyField(Employee,verbose_name = "Çalışacaklar")
    efforts = models.DurationField(verbose_name = "Projenin Süresi")
    projectStatus = models.CharField(max_length=7, choices=status, default=1,verbose_name = "Proje Durumu")
    dead_line = models.DateField(verbose_name = "Projenin Bitiş Tarihi")
    company = models.ForeignKey(Company, on_delete=models.CASCADE,verbose_name = "Proje Sahibi Şirket")
    projectPoint = models.IntegerField(default=1, verbose_name="Proje Puanı")
    complete_per = models.FloatField(max_length=2, validators=[
                                     MinValueValidator(0), MaxValueValidator(100)],verbose_name = "Tamamlanma Performansı (100 üzerinden)")
    description = models.TextField(blank=True,verbose_name = "Proje Açıklaması")

    created_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now_add=False, auto_now=True)
    
    class Meta:
        ordering = ['projectName']

    def __str__(self):
        return (self.projectName)


class ProjectDetail(models.Model):

    projectName = models.ForeignKey(
        Projects, on_delete=models.CASCADE, verbose_name="Proje İsmi")
    projectEmployee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, verbose_name="Proje Çalışanı")

    def __str__(self):
        return str(self.projectName)

class ProjectDocument(models.Model):
    project = models.ForeignKey(
        Projects,on_delete=models.CASCADE,verbose_name="Proje İsmi"
    )
    document = models.FileField(blank = True,null = True,verbose_name = "Döküman Ekleyin")

class Tasks(models.Model):

    tasksManager = models.ForeignKey(ProjectManager, on_delete = models.CASCADE)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    employees = models.ManyToManyField(Employee)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    created_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now_add=False, auto_now=True)
    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)


class ManagerEmployees(models.Model):

    managers = models.ForeignKey(
        ProjectManager, verbose_name="Yönetici", on_delete=models.CASCADE)
    employee = models.ForeignKey(
        Employee, verbose_name="Çalışan", on_delete=models.CASCADE)

class Comment(models.Model):
    project = models.ForeignKey(Projects,on_delete = models.CASCADE,verbose_name = "Proje",related_name= "comments")
    comment_author = models.CharField(max_length=50,verbose_name = "Yorum Yazarı")
    comment_content = models.CharField(max_length=200,verbose_name = "Yorum Alanı")
    comment_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date'] 

project/forms.py
from django import forms
from django.db.models import fields
from .models import Projects, ProjectDetail, Tasks, ManagerEmployees,ProjectDocument


class ProjectForms(forms.ModelForm):
    class Meta:
        model = Projects
        fields = ["projectName", "projectStatus",
                  "projectPoint", "projectManager",
                   "employees", "efforts", "dead_line",
                    "company", "complete_per", "description"]


class ProjectDetailForms(forms.ModelForm):
    class Meta:
        model = ProjectDetail
        fields = ["projectEmployee", "projectName"]


class TasksForms(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ["tasksManager","project", "employees",
                  "task_name", "status",
                  "due"]


class ManagerEmployees(forms.ModelForm):
    class Meta:
        model = ManagerEmployees
        fields = ["managers", "employee"]

class StatusDueUpdate(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ["status","due"]


class ProjectDocumentForm(forms.ModelForm):
    class Meta:
        model = ProjectDocument
        fields = ["project","document"]        

project/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ProjectForms
from .models import Projects, ProjectDetail, Tasks ,Comment
from employee.models import Employee
from p_manager.models import ProjectManager

# Create your views here.


def index(request):
    return render(request, "index.html")


@login_required(login_url="user:loginUser")
def dashboard(request):
    content = {}
    projectManager = ProjectManager.objects.filter(user=request.user)
    if projectManager:
        projects = Projects.objects.filter(
            projectManager=ProjectManager.objects.get(user=request.user))
        tasks = Tasks.objects.filter(
            tasksManager=ProjectManager.objects.get(user=request.user))
        content = {
            "projects": projects,
                "projectManager": projectManager,
                "tasks": tasks
        }
    else:
        employee = Employee.objects.filter(user=request.user)
        if employee:
            projects = Projects.objects.filter(
                employees=Employee.objects.get(user=request.user))
            tasks = Tasks.objects.filter(
                employees=Employee.objects.get(user=request.user))
            
            content = {
                "projects": projects,
                "employee": employee,
                "tasks": tasks
            }

    return render(request, "dashboard.html",content)

def projectsPage(request):
    projects = Projects.objects.all()
    keyword = request.GET.get("keyword")

    if keyword:
        projects = Projects.objects.filter(title__contains = keyword)
        return render(request,"projects.html",{"all_projects":projects})


    return render(request,"projects.html",{"all_projects":projects})



def projectDetail(request,id):
    
    project = get_object_or_404(Projects,id = id)
    comments = project.comments.all()
    context = {
        "project" : project,
        "comments" : comments
    }

    return render(request,"project-detail.html",context)

def addComment(request,id):
    project = get_object_or_404(Projects,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newCommnet = Comment(comment_author = comment_author, comment_content = comment_content)

        newCommnet.project = project

        newCommnet.save()

    return redirect(reverse("project:projectDetail",kwargs={"id":id}))

templates/addproject.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Proje Ekle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <!--{{form.media}}-->
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Proje Ekle</button>
        </form>
    </div>
</div>


{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>
<p>
  Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
{% if projectManager %}
<hr>
<a class="btn btn-danger" href="{% url 'p_manager:addprojects' %}">Proje Ekle</a>
<hr>
{% elif employee %}
<hr>
<p>Çalışan Portalı...</p>
<hr>
{% endif %}

{% if projectManager %}

{% if projects %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Proje</th>
      <th scope="col">Yönetici</th>
      <th scope="col">Tarih</th>
    </tr>
  </thead>
  <tbody>
    {% for project in projects %}
    <tr>
      <th scope="row">{{project.id}}</th>
      <td><a href="#">{{project.projectName}}</a></td>
      <td>{{project.projectManager.username}}</td>
      <td>{{project.created_date}}</td>
      <td>{{project.update_date}}</td>
      <td><a href="{% url 'p_manager:updateprojects' project.id %}" class="btn btn-info">Güncelle</a></td>
      <td><a href="{% url 'p_manager:deleteprojects' project.id %}" class="btn btn-info">Sil</a></td>

    </tr>
    {% endfor %}


  </tbody>
</table>

<br>
<br><br>

<h3>Verilen Görevler</h3>
<hr>
<a class="btn btn-danger" href="{% url 'p_manager:addtask' %}">Görev Ekle</a>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Proje</th>
      <th scope="col">Yönetici</th>
      <th scope="col">Durumu</th>
      <th scope="col">Zaman Durumu</th>
      <th scope="col">Veriliş Tarihi</th>
      <th scope="col">Güncelleme Tarihi</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      
      <th scope="row">{{task.id}}</th>
      <td><a href="#">{{task.project.projectName}}</a></td>
      <td>{{task.tasksManager.username}}</td>
      {% if task.status == "1" %}
      <td><span class="badge badge-warning">Durdu</span></td>
      {% elif task.status == "2" %}
      <td><span class="badge badge-info">Çalışıyor</span></td>
      {% else %}
      <td><span class="badge badge-success">Bitti</span></td>
      {% endif %}

      {% if task.due == "1" %}
      <td><span class="badge badge-info">Zamanı Yaklaşıyor</span>
        <a href="{% url 'employee:updatedue' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% elif task.due == "2" %}
      <td><span class="badge badge-danger">Zamanı Aştı</span>
        <a href="{% url 'employee:updatedue' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% else %}
      <td><span class="badge badge-success">Bitti</span>
        <a href="{% url 'employee:updatedue' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% endif %}
      <td>{{task.created_date}}</td>
      <td>{{task.update_date}}</td>
      <td><a href="{% url 'p_manager:updateTask' task.id %}" class="btn btn-info">İçeriği Güncelle</a></td>
      <td><a href="{% url 'p_manager:deleteTask' task.id %}" class="btn btn-info">Sil</a></td>

    </tr>
    {% endfor %}


  </tbody>
</table>

{% else %}
<diV class="alert alert-danger">Henüz Proje Bulunmuyor</diV>
{% endif %}

{% elif employee %}

{% if projects %}
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Proje</th>
      <th scope="col">Yönetici</th>
      <th scope="col">Tarih</th>
    </tr>
  </thead>
  <tbody>
    {% for project in projects %}
    <tr>
      <th scope="row">{{project.id}}</th>
      <td><a href="#">{{project.projectName}}</a></td>
      <td>{{project.projectManager.username}}</td>
      <td>{{project.created_date}}</td>
    </tr>
    {% endfor %}


  </tbody>
</table>
<br>
<br>
<br>
<h3>Görevlerim</h3>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Proje</th>
      <th scope="col">Yönetici</th>
      <th scope="col">Durumu</th>
      <th scope="col">Süre Durumu</th>
      <th scope="col">Veriliş Tarihi</th>
      <th scope="col">Güncelleme Tarihi</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <th scope="row">{{task.id}}</th>
      <td><a href="#">{{task.project.projectName}}</a></td>
      <td>{{task.tasksManager.username}}</td>
      
      {% if task.status == "1" %}
      <td><span class="badge badge-warning">Durdu</span>
        <a href="{% url 'employee:updatestatus' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% elif task.status == "2" %}
      <td><span class="badge badge-info">Çalışıyor</span>
        <a href="{% url 'employee:updatestatus' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% elif task.status == "3" %}
      <td><span class="badge badge-success">Bitti</span>
        <a href="{% url 'employee:updatestatus' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% else %}
      <td><span class="badge badge-secondary">deneme</span>
        <a href="{% url 'employee:updatestatus' task.id %}" class="btn btn-info">Güncelle</a></td>
      {% endif %}

      {% if task.due == "1" %}
      <td><span class="badge badge-info">Zamanı Yaklaşıyor</span>
        
      </td>
      {% elif task.due == "2" %}
      <td><span class="badge badge-danger">Zamanı Aştı</span>
        
      {% elif task.due == "3" %}
      <td><span class="badge badge-success">Bitti</span>
        
      {% endif %}

      <td>{{task.created_date}}</td>
      <td>{{task.update_date}}</td>
      
      
      <td><a href="#" class="btn btn-info">Sil</a></td>
    </tr>
    {% endfor %}


  </tbody>
</table>
{% else %}
<diV class="alert alert-danger">Bulunuduğunuz Proje Bulunmuyor</diV>
{% endif %}


{% endif %}
{% endblock body %}

templates/employee-register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Kayıt Ol(Çalışan)</h3>
        <hr>
        <form method="post">

            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block body %}
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">Merhaba Herkese</h1>
    <p class="lead">Dünyanın en büyük proje planlama ve yönetme uygulamasına hoşgeldin. Burada projelerini ekibinle 
      geliştirebilir ve yönetebilirsin.
    </p>
    <hr class="my-4">
    <p>Hazırsan Başlayalım...</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">Daha fazla</a>
    </p>
  </div>
</div>
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <title>Derin Team</title>
</head>

<body>
    <br>
    <br>
    <br>

    {% include "includes/navbar.html" %}

    <div style="margin-top: 100px; margin-bottom: 100px;" class="container">
        {% if messages %}

        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block body %}





    {% endblock body %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">

            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/manager-register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Kayıt Ol(Yönetici)</h3>
        <hr>
        <form method="post">

            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/project-detail.html
{% extends "layout.html" %}

{% block body %}
<!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{project.projectName}}</h1>

        <!-- Author -->
        <p class="lead">
          Yönetici:
          <a href="#">{{project.projectManager}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{project.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        <!--
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}
        <hr>
        -->
        <!-- Post Content -->
        
        
        <p>{{project.description|safe}}</p>
        <hr>
        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}
          </div>
        </div>
        
        {% endfor %}
        {% else %}
        <div class="alert alert-info">Projeye Henüz Yorum Yapılmamaış</div>
        {% endif%}
        
        <div class="card my-4">
          <h5 class="card-header">Yorum Yazın:</h5>
          <div class="card-body">
            <form method="POST" action="{% url 'project:comment' project.id %}">
              {% csrf_token %}
              <div class="form-group">
                <label for="formGroupExampleInput">Yorum Yazarı</label>
                <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput">Yorum Alanı</label>
                <textarea name="comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Yorum Ekle</button>
            </form>
          </div>
        </div>
       

      </div>

      

    </div>
    <!-- /.row -->

{% endblock body %}

templates/project-update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Proje Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <!--{{form.media}}-->
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Proje Güncelle</button>
        </form>
    </div>
</div>


{% endblock body %}

templates/projects.html
{% extends "layout.html" %}

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <h3>Projeler</h3>
            <hr>
        </div>
    </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Ara</button>
            </form>
      </div>
    </div>

</div>

{% if all_projects %}
{% for project in all_projects %}
<!-- Page Content -->


<div class="row">
    <div class="col-md-10 offset-md-3">
        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title -->
            <a href="{% url 'project:projectDetail' project.id %}">
                <h1 class="mt-4">{{project.projectName}}</h1>
            </a>

            <!-- Author -->
            <p class="lead">

                <a href="#">{{project.projectManager}}</a> tarafından yayınlandı
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Oluşturma Tarihi {{project.created_date}}</p>

            <hr>
           
            
         

        </div>
    </div>

</div>
<!-- /.row -->
{% endfor %}


{% else %}
<div class="alert alert-danger">
    Proje Bulunamadı
</div>

{% endif %}


{% endblock body %}

templates/task-add.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Görev Ekle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <!--{{form.media}}-->
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Görev Ekle</button>
        </form>
    </div>
</div>


{% endblock body %}

templates/task-update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">

        <h3>Görev Güncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <!--{{form.media}}-->
            {{form|crispy}}
            <br>
            <button typw="submit" class="btn btn-danger">Görev Güncelle</button>
        </form>
    </div>
</div>


{% endblock body %}